---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: test-heapconapp
  namespace: ernez
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~1.0
spec:
  releaseName: test-heapconapp
  chart:
    repository: https://heapcon-workshop.github.io/heapcon-chartmuseum/
    name: heapcon-app
    version: 1.0.0
  values:
    prefix: test
    namespace: ernez
    web:
      image: bdjordjevic/heapcon-web:1.0.0
    attendeeService:
      image: bdjordjevic/heapcon-attendeeservice:1.0.0
    scheduleService:
      image: bdjordjevic/heapcon-scheduleservice:1.0.0